### ISSUE TITLE
build fails with latest mpv git version

### ISSUE THREAD

**Issue by ahjolinna** [mpc-qt/mpc-qt#17]
it seems there has been some new change past two week (Dec 14-26) in (lib)MPV that causes their build to fail (at least those few I have on my obs repo) 

here is the obs build log for mpc-qt: [link](https://gist.githubusercontent.com/ahjolinna/c568f3622e6f7eae663593484b8d80ec/raw/f1b2e9732d4cd1266b4873dbb1eeb0060f2082bc/gistfile1.txt)

also I did try to build with stable (lib)mpv but when I install/update it on my system it complains of 'libavcodec.so.58.91()(64bit)' ...sigh

(if there is some help, here is [Haruna-player](https://invent.kde.org/multimedia/haruna) (by KDE) build log[: link](https://gist.githubusercontent.com/ahjolinna/a39b5239f0e4534e244dbd7506a47d8a/raw/731dac1caa0958bebf779ae3b398be9b7ada737d/gistfile1.txt) )

**Comment by cmdrkotori** [comment]
I think was fixed in b0037a28e998414f355c395e8d6a5c6d7b1ec8e7. I guess mpc-qt is overdue for a new release but there's one more thing I need to fix on Windows that I've been procrastinating before I can do that.

**Comment by ahjolinna** [comment]
weird, well apparently it wasn't fixed or something else got changed recently...as I use the latest git version of mpc-qt also: https://build.opensuse.org/package/show/home:ahjolinna/mpc-qt (Leap 15.3 build just fine as it use basic mpv, it's just the tumbleweed version that is broken that uses my git build)

**Comment by cmdrkotori** [comment]
Should be fixed now.

**Comment by ahjolinna** [comment]
yes that worked, thanks for the fast fix (and happy holidays, hopefully 2022 will be better year)
