### ISSUE TITLE
Windows Media Overlay support

### ISSUE THREAD

**Issue by matiasw** [mpc-qt/mpc-qt#33]
Hi.
I would like to add support for the Windows Media Overlay, that is, this little overlay window:
![Media Overlay](https://docs.microsoft.com/en-us/uwp/api/windows.media/images/smtc.png?view=winrt-22000)

I am willing to work on this feature myself, but I would like the support of someone from the team. I am just a hobbyist programmer.

The first thing I need help with: I have compiled and installed mpc-qt on Windows 10 using WSL(2). I can make changes to this codebase, but how would I go about adding that Windows-specific functionality? I mean, [this guide](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols) makes it seem straightforward enough: I need to add and implement a [MediaPlayer object](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Playback.MediaPlayer?view=winrt-22000) - the question is, how do I do that? I can't exactly install libmswindows-mediaplayer-dev, so how to get started writing this feature?

**Comment by cmdrkotori** [comment]
To use windows-specific code you'll need to compile it via MSYS2 and run it as a windows program. Setup guide: https://wiki.qt.io/MSYS2 and install the needed packages in the README.

**Comment by matiasw** [comment]
Ok, I am now trying to get the project compiled on Windows. 
I have opened the `mpc-qt.pro` project file from the latest git master in Qt Creator. However, I get this error trying to compile it: 
`error: 'class Ui::SettingsWindow' has no member named 'afterPlaybackDefault'`
Now, in the `settingswindow.ui` file, I can clearly see a `<widget class="QComboBox" name="afterPlaybackDefault">`, so I do not know what this error is about. 

Please help me get started with development on this feature. 

For the future, does the project have some more real-time communications channel, like a Telegram group, where I could ask about such issues that are probably easily solvable by people smarter than me?

**Comment by cmdrkotori** [comment]
The 'no member named' errors are usually resolved by doing a compile run. The *_ui.h headers are generated at compille time.

There's no telegram group or anything. I don't think this application is big enough to warrant such an investment, nor do I have the time to do so. Keep posting here and I'll get to it eventually.

**Comment by matiasw** [comment]
I have already tried doing a Clean/Build cycle, but the error persists.

**Comment by matiasw** [comment]
Ok, I finally got it compiled by running `make distclean; qmake` in a WSL prompt.

**Comment by matiasw** [comment]
I found [this project](https://github.com/datasone/MPVMediaControl) for controlling the System Media Transport Controls with mpv. Any idea if this could be used with mpc-qt without changes? In other words, is there a way to use mpv scripts with mpc-qt's (lib)mpv?

**Comment by cmdrkotori** [comment]
From experience, mpv scripts don't always work with libmpv.  It also means bundling another file.  At least the script would need to be ported to C++.

So yeah I guess that implementation would work, though it would need to be ported to C++ and run inside the process.

If you want to do this, the place to code this is either in ipc/ (if communicating to some external program) or platform/ (if it is a platform specific module that implements *all* of that project), depending on the implementation.  The appropriate slots to connect to are listed in setupMpris (a similar ipc) in main.cpp.  If doing ipc I guess it would also need its own thread because it would need to wait on the socket.  If doing an external program, it needs to be placed in the binaries folder or so to be bundled by the build scripts; but I guess you'll work the development flow out in that case.
